{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "fa1d1764",
   "metadata": {},
   "source": [
    "# Introduction to Computer Programming and Numerical Methods\n",
    "\n",
    "> **Mohamad M. Hallal, PhD** <br> Teaching Professor, UC Berkeley\n",
    "\n",
    "[![License](https://img.shields.io/badge/license-CC%20BY--NC--ND%204.0-blue)](https://creativecommons.org/licenses/by-nc-nd/4.0/)\n",
    "***"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "87237015",
   "metadata": {},
   "source": [
    "# Errors and Exceptions\n",
    "\n",
    "1. [**Error Types**](#s1)\n",
    "2. [**Exceptions**](#s2)\n",
    "3. [**Additional Reading**](#s3)\n",
    "\n",
    "***"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2e4b4ebf",
   "metadata": {},
   "source": [
    "# 0. Motivation\n",
    "\n",
    "In the previous section, we discussed numerical errors caused by how computers represent numbers. These are different from errors in a code, which can be classified into three different types: (1) syntax, (2) runtime, and (3) logical errors. Syntax errors occur when the code does not conform to the correct programming language syntax. Runtime errors (also called exceptions) occur when the code has no syntax errors but encounters exceptional situations. Logical errors occur when the code has no syntax or runtime errors and runs smoothly, but does not produce the intended result due to incorrect logic. \n",
    "\n",
    "So far, our programs have crashed whenever they have encountered a syntax or runtime error. However, runtime errors can be handled to allow the program to continue without crashing. In this section, we will discuss handling exceptions and debugging, which is the process of fixing bugs (i.e., errors).\n",
    "\n",
    "**Learning objectives:**\n",
    "\n",
    "* Distinguish between different error types\n",
    "* Identify the error type in a program\n",
    "* Fix errors in a program\n",
    "* Identify errors that can be handled \n",
    "* Design programs that handle exceptions (one or multiple exceptions)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "15086aaa",
   "metadata": {},
   "source": [
    "# 1. Error Types <a id=\"s1\"></a>\n",
    "\n",
    "Errors or mistakes in a program are often referred to as **bugs**. The process of tracking them down and correcting them is called **debugging**. It is useful to distinguish between error types in order to track them down more quickly. There are three basic types of errors that can occur:\n",
    "1. Syntax errors\n",
    "2. Runtime errors\n",
    "3. Logical errors\n",
    "\n",
    "## 1.1. Syntax Errors\n",
    "\n",
    "Syntax errors occur when the syntax of a program does not conform to the rules of the language. By now, you will have encountered many syntax errors when programming for this class. Some examples of syntax errors include:\n",
    "* trying to assign a variable to a number: `1 =  x`\n",
    "* inconsistent parentheses and/or brackets: `(1]`\n",
    "* missing quotes: `print(I like programming)`\n",
    "* missing colon: `def function_name()`\n",
    "\n",
    "Overall, syntax errors are generally easily detectable, easily found, and easily fixed.\n",
    "\n",
    "## 1.2. Runtime Errors (Exceptions)\n",
    "\n",
    "Runtime errors, also known as exceptions, occur when something goes wrong while the program is running. Some  examples of runtime errors include:\n",
    "* division by zero: `1/0`\n",
    "* performing an operation on incompatible types: `1 + [2]`\n",
    "* using a variable which has not been defined: `print(x)`\n",
    "* trying to access an index out of range: `x = [1, 2]; x[5]`\n",
    "* trying to import a misspelled/missing module: `import mat`\n",
    "\n",
    "Exceptions are more difficult to find and are only detectable by the interpreter when a program is run.\n",
    "\n",
    "## 1.3. Logical Errors\n",
    "\n",
    "Sometimes, even if there are no syntax or runtime errors, and a code runs without raising any errors, that does not necessarily mean the code is correct. Logical errors occur when the result is incorrect due to a mistake in the logic of the program. If there is a logical error, the program will run smoothly, in the sense that the computer will not generate any error messages, but the result is incorrect. Some examples of logical errors include:\n",
    "* mixing up a variable name\n",
    "* getting operator precedence wrong\n",
    "* making a mistake in logical operations\n",
    "\n",
    "Logical errors are easy to generate but very tricky to find."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a1f1c5d0",
   "metadata": {},
   "source": [
    "# 2. Exceptions <a id=\"s2\"></a>\n",
    "\n",
    "Until now, our programs have crashed whenever they have encountered a syntax or runtime error. Instead of letting the error crash our program, it would be nice if we can intercept it, handle it gracefully, and allow the program to continue. Syntax errors cannot be handled and are always fatal (a program with syntax error will always crash). However, runtime errors are not fatal â€“ we can write our code to *handle* exceptions gracefully and allow the program to continue running instead of crashing. By handling exceptions, we can instruct our program to take alternative actions when a runtime error occurs.\n",
    "\n",
    "## 2.1. USS Yorktown\n",
    "\n",
    "One example where handling exceptions would have been helpful is the USS Yorktown, a cruiser in the United States Navy from 1984 to 2004. From 1996, Yorktown was used as the testbed for the Navy's Smart Ship program. On 21 September 1997, while on maneuvers off the coast of Cape Charles, Virginia, a crew member entered a zero into a database field, causing an attempted division by zero in the ship's Remote Data Base Manager. This error brought down all the machines on the network, causing the ship's propulsion system to fail and the ship to stop dead in the water.\n",
    "\n",
    "<br>\n",
    "<center><figure>\n",
    "  <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/USS_Yorktown_%28CG-48%29_2002.jpg/600px-USS_Yorktown_%28CG-48%29_2002.jpg\" style=\"width:35%\">\n",
    "    <figcaption style=\"text-align:center\"><strong><br> USS Yorktown on 24 February 2002:</strong> <a href=\"https://en.wikipedia.org/wiki/USS_Yorktown_(CG-48)#Smart_ship_testbed\">https://en.wikipedia.org/</a></figcaption>   \n",
    "</figure></center>\n",
    "<br>\n",
    "\n",
    "Several lessons can be learned from this event that are useful for software development professionals:\n",
    "* Programs should be designed to validate input data before processing it\n",
    "* Programs should also catch and handle exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "49b547ae",
   "metadata": {},
   "source": [
    "## 2.2. Raising Exceptions\n",
    "\n",
    "When an issue arises during program execution, Python raises an exception to indicate that something has gone wrong. While Python performs some built-in checks, it's essential to implement your own checks and provide informative error messages to clarify the problem.\n",
    "\n",
    "To raise an exception with a custom message, you can use the following syntax:\n",
    "\n",
    "```python\n",
    "raise ExceptionType(\"Message to display\")\n",
    "```\n",
    "\n",
    "where `ExceptionType` [built-in exception types](https://docs.python.org/3/library/exceptions.html#bltin-exceptions) available in Python. Choose the exception type that best describes the encountered error. If none of the built-in exceptions accurately represents the error, you can use `RuntimeError`.\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Modify the function below to raise a <code>ValueError</code> with the message <code>\"Divisor cannot be zero.\"</code> when it is called with <code>divisor = 0</code>.</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4a68d20",
   "metadata": {},
   "outputs": [],
   "source": [
    "def division(dividend, divisor):\n",
    "    if divisor == 0:\n",
    "        # raise exception\n",
    "        \n",
    "    print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "        \n",
    "division(5, 0)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7e997286",
   "metadata": {},
   "source": [
    "## 2.3. Handling Exceptions\n",
    "\n",
    "Still, in the example above, the error caused the program to crash. We can alternatively write our code to handle exceptions and allow the program to continue to run instead of crashing. Exceptions can be handled using a `try` and `except` statement, which is similar to `if` and `else`. The syntax is:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # attempt code block 1\n",
    "except ExceptionType:\n",
    "    # If an 'ExceptionType' exception is raised above, do code block 2 \n",
    "```\n",
    "\n",
    "where:\n",
    "* `code block 1` is a code that might raise an exception\n",
    "* `ExceptionType` is the exception [type](https://docs.python.org/3/library/exceptions.html#bltin-exceptions) that you want to handle (e.g., `NameError`, etc.)\n",
    "* `code block 2` is what will be executed if `code block 1` raises an exception that matches `ExceptionType`\n",
    "\n",
    "Python's behavior with try and except is straightforward:\n",
    "1. Python will first attempt to execute the code in the `try` statement (code block 1).\n",
    "2. If no exception occurs during the execution of code block 1, the `except` statement (code block 2) is skipped, and the program continues executing the code outside the `try`/`except` construct.\n",
    "3. If any exception occurs while executing code block 1, the flow of control will immediately shift to the `except` statement. \n",
    "4. If the type of the raised exception matches `ExceptionType`, the code in the `except` statement (code block 2) will be executed. \n",
    "5. If nothing in the `except` block stops the program, it will continue to execute the rest of the code outside of the `try`/`except` code block.\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Run the following code. Input a letter (not a number) and examine the error:\n",
    "    \n",
    "<pre>\n",
    "dividend = int(input(\"Please enter the dividend: \"))\n",
    "divisor = int(input(\"Please enter the divisor: \"))\n",
    "print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "</pre>\n",
    "    \n",
    "</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2fb9abb",
   "metadata": {},
   "outputs": [],
   "source": [
    "dividend = int(input(\"Please enter the dividend: \"))\n",
    "divisor = int(input(\"Please enter the divisor: \"))\n",
    "print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "print('This statement does not run!')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f0e73530",
   "metadata": {},
   "source": [
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Try to handle the <code>ValueError</code> and print the following if it occurs: \"The input should be an integer\".</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a46319ea",
   "metadata": {},
   "outputs": [],
   "source": [
    "# add try except\n",
    "\n",
    "# code after try/except\n",
    "print('This statement runs!')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b96d65ec",
   "metadata": {},
   "source": [
    "If the exception type does not match `ExceptionType`, the execution stops and an error is raised.\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Input 0 for the divisor and examine the error.</div>\n",
    "\n",
    "Inputting 0 for the divisor raises a `ZeroDivisionError`, which does not match the error type after `except` (i.e., `ValueError`), and thus, the error in this case is not handled and the program crashes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b6750af",
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    dividend = int(input(\"Please enter the dividend: \"))\n",
    "    divisor = int(input(\"Please enter the divisor: \"))\n",
    "    print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "except ValueError:\n",
    "    print(\"The input should be an integer\")\n",
    "    \n",
    "print('This statement does not run!')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e75ca78",
   "metadata": {},
   "source": [
    "## 2.4. Handling Multiple Exceptions\n",
    "\n",
    "A `try` statement may have more than one `except` statement to handle different types of exceptions. Alternatively, a general `except` statement can be used without specifying `ExceptionType` to catch any exception type that occurs within the try block:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # attempt code block 1\n",
    "except:\n",
    "    # If ANY exception is raised above, do code block 2 \n",
    "```\n",
    "\n",
    "In this case, **all** exceptions, of any type, will be handled. This, however, *is not a good idea*. What if we got an error that we hadn't predicted? It would be handled as well, and we wouldn't even notice that anything unusual was going wrong. \n",
    "\n",
    "**Example that handles ALL exception types:**\n",
    "\n",
    "```python\n",
    "try:\n",
    "    dividend = int(input(\"Please enter the dividend: \"))\n",
    "    divisor = int(input(\"Please enter the divisor: \"))\n",
    "    print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "except:\n",
    "    print(\"The input(s) is(are) incorrect\")\n",
    "```\n",
    "\n",
    "**Example that handles multiple exception types:**\n",
    "\n",
    "```python\n",
    "try:\n",
    "    dividend = int(input(\"Please enter the dividend: \"))\n",
    "    divisor = int(input(\"Please enter the divisor: \"))\n",
    "    print(\"%d / %d = %f\" % (dividend, divisor, dividend/divisor))\n",
    "except ValueError:\n",
    "    print(\"The divisor and dividend have to be numbers\")\n",
    "except ZeroDivisionError:\n",
    "    print(\"The divisor may not be zero\")\n",
    "```\n",
    "\n",
    "Exception handling gives us an alternative way to deal with error-prone situations in our code. However, `try/except` statements should never be used in place of good programming practice. You should not code sloppily and then encase your program in many `try/except` statements until you have taken every measure you can think of to ensure that your function is working properly."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "46ddfe84",
   "metadata": {},
   "source": [
    "# 3. Additional Reading <a id=\"s3\"></a>\n",
    "\n",
    "## 3.1. Using `assert` Statements\n",
    "\n",
    "When testing a program, it's essential to test for both valid and invalid input data. For example, if you are writing a function that takes in an integer and squares it, it might be useful to ensure that your input is in fact an integer. A helpful tool for this is the `assert` keyword, which can be used to enforce conditions and assumptions in your code.\n",
    "\n",
    "Assertions are boolean expressions that check whether a given condition holds true or not.  If the condition is true, the program continues executing without any interruption. However, if the condition evaluates to false, an exception is raised, halting the program's execution.\n",
    "\n",
    "The basic syntax of an `assert` statement is as follows:\n",
    "\n",
    "```python\n",
    "assert condition, \"Error Message\"\n",
    "```\n",
    "where:\n",
    "* `condition` is an expression or condition you want to check\n",
    "* `\"Error Message\"` is an optional error message as a string to clarify why the assertion failed\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Modify the function below to assert that the type of <code>x</code> is an integer before squaring it.</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df9726bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "def square_number(x):\n",
    "    # Add assert statement followed by an error message\n",
    "    \n",
    "    sq = x ** 2\n",
    "    return sq\n",
    "\n",
    "# call the function with invalid input\n",
    "square_number('10')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f202fdb0",
   "metadata": {},
   "source": [
    "So now, when the assert statement fails, we receive a clear error indicating that the argument to `square_number()` must be an integer. This allows us to quickly narrow down the problem.\n",
    "\n",
    "A useful function to check the data type of an object is the `isinstance()` function, which has the following syntax:\n",
    "\n",
    "```python\n",
    "isinstance(object, classinfo)\n",
    "```\n",
    "\n",
    "where:\n",
    "* `object` is the object or variable you want to check\n",
    "* `classinfo` is a class, type, or tuple of classes and types\n",
    "\n",
    "The function returns `True` if `object` is an instance or a subclass of `classinfo`, `False` otherwise.\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Modify the function below to assert that the type of <code>x</code> is an integer or float using <code>isinstance()</code> before squaring it.</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b7ff628",
   "metadata": {},
   "outputs": [],
   "source": [
    "def square_number(x):\n",
    "    # Add assert statement with instance followed by an error message\n",
    "    \n",
    "    sq = x ** 2\n",
    "    return sq\n",
    "\n",
    "# call the function with invalid input\n",
    "square_number('10')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c0cae324",
   "metadata": {},
   "source": [
    "## 3.2. Debugging\n",
    "\n",
    "Even with best practices, errors will occur. So, it is important to be able to identify and fix them. Errors are often referred to as bugs, and the process of tracking them down and correcting them is called debugging. One of the most important skills you will acquire is debugging. Although it can be frustrating, debugging is one of the most intellectually challenging and interesting parts of programming. In some ways, debugging is like detective work. You are confronted with errors or results that are not what you expect. These are your clues to infer what led to the results you see.\n",
    "\n",
    "When Python raises an error, look at what type of error it is to help narrow your search. Also check that you aren't making any common mistakes (e.g., spelling, missing parentheses, missing quotes, = versus ==, etc.). If the cause of the error is not obvious, there are different debugging techniques, and we discuss some of these techniques below.\n",
    "\n",
    "### 3.2.1. Using `print()` \n",
    "\n",
    "When you first learn how to program, it can be hard to spot bugs in your code. One common practice is to insert `print()` statements at different lines to check how the output is changing. This will output the intermediate results which were calculated on that line. Most programmers intuitively do this as they are writing a function, or perhaps if they need to figure out why it isn't doing the right thing.\n",
    "\n",
    "For example, let's say the following function `f1()` keeps returning an error or incorrect result:\n",
    "\n",
    "```python\n",
    "def f1(x):\n",
    "    result = f2(x)\n",
    "    return result * 10\n",
    "```\n",
    "\n",
    "We can add a `print()` statement before the return to check what `f2()` is returning:\n",
    "\n",
    "```python\n",
    "def f1(x):\n",
    "    result = f2(x)\n",
    "    print('f2 result: ', result)\n",
    "    return result * 10\n",
    "```\n",
    "\n",
    "If it turns out `result` is not what we expect it to be, we would go look in `f2()` to see if it works properly. \n",
    "\n",
    "When using `print()` statements for debugging, here are a few good practices to follow:\n",
    "\n",
    "* Don't just print out a variable â€“ add some sort of message to make it easier for you to read\n",
    "```python \n",
    "print(result) # harder to keep track\n",
    "print(f'f2 result: {result}') # easier\n",
    "```\n",
    "* Use `print()` statements to view the results of function calls (i.e. after function calls)\n",
    "* Use `print()` statements at the end of a loop to view the state of the counter variables after each iteration\n",
    "```python \n",
    "i = 0\n",
    "while i < n:\n",
    "    i += f1(i)\n",
    "    print(f'counter i is {i}')\n",
    "```\n",
    "* Don't just put random `print()` statements after lines that are obviously correct\n",
    "\n",
    "The `print()` statements described above are meant for quick debugging of one-time errors â€“ after figuring out the error, you would remove all the `print()` statements. However, sometimes we would like to leave the debugging code if we need to periodically test our file. It can get kind of annoying if every time we run our file, debugging messages pop up. One way to avoid this is to use a global debug variable:\n",
    "\n",
    "```python\n",
    "debug = True\n",
    "\n",
    "def f1(x):\n",
    "    result = f2(x)\n",
    "    if debug:\n",
    "        print('f2 result: ', result)\n",
    "    return result * 10\n",
    "```\n",
    "\n",
    "Now, whenever we want to do some debugging, we can set the global `debug` variable to `True`, and when we don't want to see any debugging input, we can turn it to `False` (such a variable is called a \"flag\").\n",
    "\n",
    "### 3.2.2. Interactive Debugging\n",
    "\n",
    "Python has functionalities that can assist you when debugging. The standard debugging tool in Python is `pdb` (Python DeBugger) for interactive debugging. It lets you step through the code line by line to find out what might be causing a difficult error. We won't cover too much about it here, you can check out the [documentation for details](https://docs.python.org/3/library/pdb.html).\n",
    "\n",
    "There are two ways you could debug your code, (1) activate the debugger after you run into an exception; (2) activate debugger before you run the code. Both work very similarly, so we will only demonstrate activating the debugger *after* an exception is raised.\n",
    "\n",
    "After an exception is raised, you could activate the debugger by using the command `%debug`, which will open an interactive debugger for you.\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Run the code below and then active the debugger using <code>%debug</code>. When the debugger is activated, enter <code>h</code> to get a list of helpful commands.</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b3214c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell first, which will raise an error\n",
    "# Then run the next cell and enter h\n",
    "def square_number(x):\n",
    "    x += x\n",
    "    sq = x**2\n",
    "    z\n",
    "    return sq\n",
    "\n",
    "square_number('10')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2c0fcfc1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell and type h, then hit Enter\n",
    "%debug"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "454fb3f7",
   "metadata": {},
   "source": [
    "You can type in commands in the debugger to get useful information. Some of the most frequent commands you can type are:\n",
    "\n",
    "* `h` to get a list of help\n",
    "* `p x` to print the value of variable `x` (you can replace `x` with any variable in your code)\n",
    "* `type(x)` to get the type of variable `x`\n",
    "* `p locals()` to print out all the local variables\n",
    "* `l` to list source code for the current file\n",
    "* `q` to quit the debugger\n",
    "\n",
    "It is often very useful to insert a breakpoint into your code. A breakpoint is a line in your code at which Python will stop when the function is run. This will allow you to to investigate the result up to this point in the code. To add a breakpoint, use `pdb.set_trace()`. The program stops at this line, and activate the `pdb` debugger. We could check all the variable values before this line. Then, you can use the command `c` to continue the execution.\n",
    "\n",
    "<div class=\"alert alert-block alert-warning\"> <b>NOTE!</b> To add a breakpoint, you have to first run <code>import pdb</code>.</div>\n",
    "\n",
    "<div class=\"alert alert-block alert-info\"> <b>TRY IT!</b> Run the code below and then investigate the variable <code>x</code> after the debugger is activated.</div>"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24753a51",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Run this cell\n",
    "# Then, investigate the input x up to pdb.set_trace()\n",
    "# First, type `p locals()` to print out all the local variables\n",
    "# Then, type `p x` to print the value of variable x\n",
    "# Third, type `type(x)` to get the type of variable x\n",
    "# Finally, type `c`, which will continue to run the program after pdb.set_trace(), resulting in an error\n",
    "import pdb\n",
    "def square_number(x):\n",
    "    x += x\n",
    "    pdb.set_trace()  # add a breakpoint here\n",
    "    sq = x ** 2\n",
    "    return sq\n",
    "\n",
    "square_number('10')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
